
/* tslint:disable */
/* eslint-disable */
/**
 * BillingClient
 *
 * NOTE: This class is auto generated by ts-morph
 * Do not edit the class manually.
 */

import { BillingNotificationsApi,BillingStatusApi,InvoiceApi } from '../models/billing';
import { Configuration } from '../models/configuration';
import { DEFAULT_API_BASE_PATH, APIConfigurationParameters } from '../../constants';
import { getAxiosInstance, applyMixins } from '../../helpers';

export class BillingClient extends BillingNotificationsApi {
  constructor(parameters: APIConfigurationParameters) {
    const axios = getAxiosInstance(parameters)
    const configuration = new Configuration(parameters)
    super(configuration, DEFAULT_API_BASE_PATH, axios)
  }
}


    export interface BillingClient extends BillingNotificationsApi,BillingStatusApi,InvoiceApi {}
    applyMixins(BillingClient, [BillingNotificationsApi,BillingStatusApi,InvoiceApi])
    
