
/* tslint:disable */
/* eslint-disable */
/**
 * LocalizationClient
 *
 * NOTE: This class is auto generated by ts-morph
 * Do not edit the class manually.
 */

import { CurrencyLocalizationApi,KeywordLocalizationApi,ProductLocalizationApi,TargetingExpressionLocalizationApi } from '../models/localization';
import { Configuration } from '../models/configuration';
import { DEFAULT_API_BASE_PATH, APIConfigurationParameters } from '../../constants';
import { getAxiosInstance, applyMixins } from '../../helpers';

export class LocalizationClient extends CurrencyLocalizationApi {
  constructor(parameters: APIConfigurationParameters) {
    const axios = getAxiosInstance(parameters)
    const configuration = new Configuration(parameters)
    super(configuration, DEFAULT_API_BASE_PATH, axios)
  }
}


    export interface LocalizationClient extends CurrencyLocalizationApi,KeywordLocalizationApi,ProductLocalizationApi,TargetingExpressionLocalizationApi {}
    applyMixins(LocalizationClient, [CurrencyLocalizationApi,KeywordLocalizationApi,ProductLocalizationApi,TargetingExpressionLocalizationApi])
    
