/* tslint:disable */
/* eslint-disable */
/**
 * ProductMetadataClient
 *
 * NOTE: This class is auto generated by ts-morph
 * Do not edit the class manually.
 */

import { ProductSelectorApi } from '../models/product-metadata';
import { Configuration } from '../models/configuration';
import { DEFAULT_API_BASE_PATH, getAxiosInstance, APIConfigurationParameters, applyMixins } from '../../constants';

export class ProductMetadataClient extends ProductSelectorApi {
	constructor(parameters: APIConfigurationParameters) {
		const axios = getAxiosInstance(parameters);
		const configuration = new Configuration(parameters);
		super(configuration, DEFAULT_API_BASE_PATH, axios);
	}
}
